services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "7070:8080"
      - "50000:50000"
    user: root
    volumes:
      - ./volumes/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /c/Users/SunMin/backend1/backendProject:/var/jenkins_home/workspace/backend1_local # 프로젝트 연결
    restart: unless-stopped
